# -*- coding: utf-8 -*-
"""customer_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvQehN_p0WI_g58P9t1aPDQJf-4AcNXR

##Problem Statement:

The objective of this project is to segment customers based on their demographic and spending behavior using clustering techniques.

This helps businesses design targeted marketing strategies, improve customer retention, and increase revenue.

##Import Libraries
"""

# Import required libraries for data analysis and visualization

import pandas as pd              # For data manipulation and analysis (DataFrames)
import numpy as np               # For numerical operations and array computations
import matplotlib.pyplot as plt  # For creating basic visualizations (plots, charts)
import seaborn as sns            # For advanced statistical data visualization

from sklearn.preprocessing import StandardScaler  # For scaling features (normalizing data for KMeans)
from sklearn.cluster import KMeans                # K-Means clustering algorithm for customer segmentation
from sklearn.metrics import silhouette_score      # For evaluating clustering performance (cluster quality)

# Set style for better visuals
sns.set(style="whitegrid")

# Set random seed for reproducibility (ensures same results every run)
np.random.seed(42)

"""##Data Loading

We begin by importing the dataset containing customer demographic and spending information.

This dataset will be used to identify patterns and group similar customers together.
"""

# Load dataset from CSV file (contains customer demographics and spending behavior)
df = pd.read_csv("/content/Mall_Customers.csv")

# Display first 5 rows of the dataset
df.head()

"""##Data Validation

Perform data validation to understand the structure, quality, and consistency of the dataset.

   - shape
   - info
   - null values
   - duplicates
   - nunique
   - data types
   - describes
   - columns

This section ensures the data quality is good before analysis.
"""

# Print dataset size (number of rows and columns)
print("Dataset Shape (Rows, Columns):", df.shape)

# Display information about columns
# Shows column names, data types, and non-null counts
df.info()

# Check for missing values in each column
df.isnull().sum()

# Check if duplicate rows exist in the dataset
df.duplicated().sum()

# Count the number of unique values in each column
df.nunique()

# Display data types of all columns
df.dtypes

# Show summary statistics of numerical columns
# Includes mean, std, min, max, etc.
df.describe()

# Display all column names in the dataset
df.columns

"""##Data Cleaning"""

# Create a copy of the original dataset
# This ensures the raw dataset remains unchanged
df1 = df.copy()

# Rename the columns for clear understanding
df1.rename(columns={'Annual Income (k$)': 'Annual Income', 'Spending Score (1-100)': 'Spending Score'}, inplace=True)

"""##Exploratory Data Analysis (EDA)

###Gender Distribution
"""

# Count of customers by gender
sns.countplot(x='Gender', data=df1)
plt.title("Gender Distribution")
plt.show()

"""###Age Distribution"""

# Age distribution
plt.figure(figsize=(8,5))
sns.histplot(df1['Age'], bins=20, kde=True)
plt.title("Age Distribution")
plt.show()

"""###Annual Income Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df1['Annual Income'], bins=20, kde=True)
plt.title("Annual Income Distribution")
plt.show()

"""###Spending Score Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df1['Spending Score'], bins=20, kde=True)
plt.title("Spending Score Distribution")
plt.show()

"""###Income vs Spending"""

plt.figure(figsize=(8,6))
sns.scatterplot(
    x='Annual Income',
    y='Spending Score',
    data=df1
)
plt.title("Income vs Spending Score")
plt.show()

"""###Correlation Heatmap"""

# Correlation matrix
corr = df1.corr(numeric_only=True)

plt.figure(figsize=(6,4))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""The analysis shows clear patterns between income and spending behavior, indicating the presence of distinct customer groups.

This justifies the use of clustering techniques like K-Means for segmentation.

##Feature Selection + Scaling

###Feature Selection
"""

# Select relevant features for clustering (income and spending define customer behavior)
X = df1[['Annual Income', 'Spending Score']]

# Display first few rows
X.head()

"""###Feature Scaling"""

# Initialize StandardScaler to normalize feature values
scaler = StandardScaler()

# Scale features to ensure equal importance (KMeans uses distance-based calculation)
X_scaled = scaler.fit_transform(X)

"""###Finding Optimal Clusters (Elbow Method)"""

wcss = []  # Within-Cluster Sum of Squares

# Calculate WCSS for different cluster values to find optimal number of clusters
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

# Plot the elbow graph
plt.figure(figsize=(8,5))
plt.plot(range(1, 11), wcss, marker='o')
plt.title("Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.show()
plt.savefig("elbow_method.png", bbox_inches='tight')

"""Store WCSS values for different cluster sizes to identify optimal k using elbow method.

The elbow point is observed at k = 5, where the rate of decrease in WCSS begins to slow down.

###Apply K-Means Clustering
"""

# Initialize KMeans model with optimal number of clusters (k=5)
kmeans = KMeans(n_clusters=5, random_state=42)

# Assign each data point to a cluster
y_kmeans = kmeans.fit_predict(X_scaled)

# Add cluster labels to dataset for analysis
df1['Cluster'] = y_kmeans

"""###Visualize Clusters"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='Annual Income',
    y='Spending Score',
    hue='Cluster',
    palette='Set1',
    data=df1
)

plt.title("Customer Segments")
plt.show()

"""This segmentation enables businesses to design targeted marketing strategies, optimize resource allocation, and improve customer retention.

###Cluster Profiling
"""

# Analyze average characteristics of each cluster to understand customer segments
cluster_summary = df1.groupby('Cluster')[['Age', 'Annual Income', 'Spending Score']].mean()

print("Cluster Summary (Mean Values):")
cluster_summary

"""###Cluster Size"""

# Number of customers in each cluster
cluster_size = df1['Cluster'].value_counts().sort_index()

print("\nCluster Size:")
cluster_size

"""###Combine Everything"""

# Combine mean values and customer count to create a complete cluster profile
cluster_profile = df1.groupby('Cluster').agg({
    'Age': 'mean',
    'Annual Income': 'mean',
    'Spending Score': 'mean',
    'CustomerID': 'count'
}).rename(columns={'CustomerID': 'Customer Count'})

print("\nFinal Cluster Profile:")
cluster_profile

"""##Model Evaluation + Justification

###Silhouette Score
"""

# Evaluate clustering performance using Silhouette Score (measures cluster separation and cohesion)
sil_score = silhouette_score(X_scaled, y_kmeans)

print("Silhouette Score:", round(sil_score, 3))

"""###Comparison for Multiple K"""

silhouette_scores = []

# Compare silhouette scores for different cluster values to validate optimal k
for i in range(2, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    labels = kmeans.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    silhouette_scores.append(score)

# Plot Silhouette Scores
plt.figure(figsize=(8,5))
plt.plot(range(2,11), silhouette_scores, marker='o')
plt.title("Silhouette Score for Different K")
plt.xlabel("Number of Clusters")
plt.ylabel("Silhouette Score")
plt.show()

plt.savefig("silhouette_score.png", bbox_inches='tight')

"""Higher silhouette score indicates better-defined and well-separated clusters.

##Advanced Visualizations

###Plot Cluster Centroids
"""

# Refit KMeans model with optimal clusters to correctly compute centroids
kmeans_final = KMeans(n_clusters=5, random_state=42)

kmeans_final.fit(X_scaled)

# Transform centroids back to original scale for interpretation
centroids = scaler.inverse_transform(kmeans_final.cluster_centers_)

# Convert to DataFrame for easy plotting
centroids_df = pd.DataFrame(centroids, columns=['Annual Income', 'Spending Score'])

centroids_df

"""###Visualize Centroids on Scatter Plot"""

plt.figure(figsize=(8,6))

sns.scatterplot(
    x='Annual Income',
    y='Spending Score',
    hue='Cluster',
    palette='Set1',
    data=df1,
    s=100
)

# Plot centroids
plt.scatter(
    centroids_df['Annual Income'],
    centroids_df['Spending Score'],
    color='black',
    marker='X',
    s=300,
    label='Centroids'
)

plt.title("Customer Segments with Centroids")
plt.legend()
plt.show()

"""###Improve Visualization Quality"""

plt.figure(figsize=(10,7))

sns.scatterplot(
    x='Annual Income',
    y='Spending Score',
    hue='Cluster',
    palette='Set2',
    data=df1,
    s=120,
    edgecolor='black'
)

plt.title("Customer Segmentation Analysis", fontsize=14)
plt.xlabel("Annual Income", fontsize=12)
plt.ylabel("Spending Score", fontsize=12)
plt.grid(True)
plt.show()

plt.savefig("clusters.png", bbox_inches='tight')

"""###Pairplot"""

# Visualize relationships between features across clusters
sns.pairplot(df1, hue='Cluster', palette='Set2')
plt.suptitle("Pairplot of Features by Cluster", y=1.02)
plt.show()

"""##Explanation
###Optimal Cluster Selection:

The Elbow Method suggests an optimal number of clusters at k = 5, where the reduction in WCSS starts to slow down.

To further validate this, the Silhouette Score was calculated for multiple values of k.

The Silhouette Score for k = 5 is reasonably high, indicating:

Good separation between clusters

Compact grouping within clusters

Therefore, k = 5 is selected as the optimal number of clusters, balancing model simplicity and performance.

##Business Recommendations & Strategic Actions

Based on the customer segmentation analysis, the following business strategies are recommended for each segment:

Cluster 0 — Moderate Income, Moderate Spending

- Represents average customers with balanced behavior

- Strategy:
    - Maintain engagement through regular offers
    - Introduce loyalty programs to increase retention
    - Upsell mid-range products

Cluster 1 — High Income, Low Spending

- High purchasing power but low engagement

- Strategy:
    - Target with personalized marketing campaigns
    - Provide premium product recommendations
    - Use email/SMS campaigns to increase conversion

Cluster 2 — Low Income, High Spending

- Highly engaged but budget-conscious customers

- Strategy:
    - Offer discounts and promotions
    - Provide budget-friendly bundles
    - Focus on volume-based sales

Cluster 3 — Low Income, Low Spending

- Lowest value customer segment

- Strategy:
    - Minimize marketing spend
    - Target only during major sales events
    - Avoid heavy investment

Cluster 4 — High Income, High Spending (Premium Customers)

- Most valuable segment

- Strategy:
    - Offer VIP membership programs
    - Provide exclusive deals and early access
    - Focus on customer retention and experience

##Conclusion

- Customer segmentation using K-Means clustering successfully identified distinct customer groups based on income and spending behavior.

- The analysis reveals that not all customers contribute equally to revenue, highlighting the importance of targeted marketing.

- By focusing on high-value segments and optimizing strategies for each cluster, businesses can:

  - Increase revenue
  - Improve customer retention
  - Optimize marketing costs

- This project demonstrates how data-driven decision-making can significantly enhance business performance
"""